import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

// --- Layer arrows (CLAUDE.md "Local layout") ------------------------------------
//   app/, components/, api/  ->  agents/  ->  {model, guardrails, observability, schemas}
// Each rule is a regex over the import specifier, matching relative (`../../x`) and
// alias (`@/src/x`) forms alike. ESLint does not merge `no-restricted-imports` options
// across config entries — the last matching entry wins — so every directory entry
// below lists its full rule set, built from these pieces.
const REL = String.raw`^(\.{1,2}/|@/)(.*/)?`;

const NO_UI = {
  regex: `${REL}(app|components)(/|$)`,
  message: "Agent layers must not import the SPA (app/, components/) — it would drag React into api/.",
};
const NO_EVALS = {
  regex: `${REL}evals(/|$)`,
  message: "Nothing imports src/evals/ — the harness imports agents, never the reverse.",
};
const NO_RECORDER = {
  regex: String.raw`(^|/)observability/recorder$`,
  message: "The recorder (service role) is written only through the gateway (src/model/) or api/.",
};
const NO_SDK = {
  regex: String.raw`^(ai|@ai-sdk/[^/]+)(/.*)?$`,
  message: "Model SDKs are imported only in src/model/ — call callModel() from src/model/gateway.",
};
const NO_AGENTS = {
  regex: `${REL}agents(/|$)`,
  message: "Lower and shared layers (lib, model, guardrails, observability, schemas, types) must not import agents.",
};
// UI zone: components reach agents through /api or pure agent functions, never the
// gateway or telemetry. The match is on the last path segment, so it also catches an
// agent's own `agents/*/model` — the model-backed path, which is server-only too.
const NO_MODEL = {
  regex: `${REL}model(/|$)`,
  message: "The UI never imports src/model/ (or an agent's model.ts) — call /api and fall back to the agent's heuristic.",
};
const NO_OBSERVABILITY = {
  regex: `${REL}observability(/|$)`,
  message: "The UI never imports src/observability/ — telemetry is written server-side.",
};

const restrict = (...patterns) => ({
  "no-restricted-imports": ["error", { patterns }],
});

export default tseslint.config(
  // `supabase/.temp/` is generated by `supabase start` and holds the bundled, minified
  // edge-runtime entrypoint. It is already git-ignored (supabase/.gitignore), but `eslint .`
  // does not read gitignore, so linting it reported ~190 errors in vendored output whenever
  // the local stack happened to be running — a gate that passed or failed based on Docker
  // state rather than on the source.
  { ignores: ["dist", "supabase/.temp"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
    },
  },

  // Base: everything outside the directories below (configs, vite-level files).
  { files: ["**/*.{ts,tsx}"], rules: restrict(NO_EVALS, NO_RECORDER, NO_SDK) },
  {
    files: ["src/{app,components}/**/*.{ts,tsx}"],
    rules: restrict(NO_EVALS, NO_RECORDER, NO_SDK, NO_MODEL, NO_OBSERVABILITY),
  },
  // Shared infrastructure: imports nothing above it — no UI, no agent code.
  {
    files: ["src/lib/**/*.{ts,tsx}"],
    rules: restrict(NO_UI, NO_EVALS, NO_RECORDER, NO_SDK, NO_AGENTS),
  },
  {
    files: ["src/agents/**/*.{ts,tsx}"],
    rules: restrict(NO_UI, NO_EVALS, NO_RECORDER, NO_SDK),
  },
  {
    files: ["src/{guardrails,schemas,types}/**/*.{ts,tsx}"],
    rules: restrict(NO_UI, NO_EVALS, NO_RECORDER, NO_SDK, NO_AGENTS),
  },
  // The gateway: the one place model SDKs and the recorder are imported.
  { files: ["src/model/**/*.{ts,tsx}"], rules: restrict(NO_UI, NO_EVALS, NO_AGENTS) },
  {
    files: ["src/observability/**/*.{ts,tsx}"],
    rules: restrict(NO_UI, NO_EVALS, NO_SDK, NO_AGENTS),
  },
  // The harness may import itself and agents, but goes through the gateway for models.
  { files: ["src/evals/**/*.{ts,tsx}"], rules: restrict(NO_UI, NO_RECORDER, NO_SDK) },
  // Handlers may record directly (e.g. a deterministic-path run) but call models via the gateway.
  { files: ["api/**/*.ts"], rules: restrict(NO_UI, NO_EVALS, NO_SDK) },
);
