import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `supabase/.temp/` is generated by `supabase start` and holds the bundled, minified
  // edge-runtime entrypoint. It is already git-ignored (supabase/.gitignore), but `eslint .`
  // does not read gitignore, so linting it reported ~190 errors in vendored output whenever
  // the local stack happened to be running — a gate that passed or failed based on Docker
  // state rather than on the source.
  { ignores: ["dist", "supabase/.temp"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
    },
  },
);
