import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `supabase/.temp/` is generated by `supabase start` and holds the bundled, minified
  // edge-runtime entrypoint. It is already git-ignored (supabase/.gitignore), but `eslint .`
  // does not read gitignore, so linting it reported ~190 errors in vendored output whenever
  // the local stack happened to be running — a gate that passed or failed based on Docker
  // state rather than on the source.
  { ignores: ["dist", "supabase/.temp"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
    },
  },

  // Legacy SPA surface, 2026-08-21. eslint had never run in this repo — `lint` was
  // `tsc --noEmit` — so turning it on reported 31 pre-existing errors in code nobody was
  // asked to change. Downgrading the two offending rules HERE, rather than globally or
  // via inline disables, keeps them as hard errors everywhere else and for every new
  // file, and keeps the count visible in the gate output instead of hidden.
  //
  // This block shrinks as `src/` is refactored by issue and is deleted when the count
  // reaches zero. Do not widen it, and do not add rules to it to make new code pass.
  {
    files: [
      "src/components/**/*.{ts,tsx}",
      "src/lib/**/*.ts",
      "src/types.ts",
      "src/App.tsx",
    ],
    rules: {
      "@typescript-eslint/no-unused-vars": "warn",
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
);
